### ISSUE TITLE
apple

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [CongLeSolutionX/Apple-Music#2]
hello from Greece!!!please any demo web?I have no idea from programming and I dont know how to make it!!!I am begging youuuuuuuuuuu!!!

**Comment by CongLeSolutionX** [comment]
Hi KENPOKASMMA1982, this is an iOS mobile app using Apple music API. Sure, I will think of a web version for this repo. Thanks

**Comment by CongLeSolutionX** [comment]
> hello from Greece!!!please any demo web?I have no idea from programming and I dont know how to make it!!!I am begging youuuuuuuuuuu!!!

Hi KENPOKASMMA1982, this is an iOS mobile app using Apple music API. Sure, I will think of a web version for this repo. Thanks
